version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-localdev
    command: bash -c "stack install && scrabble-scotty-app-exe"
    image: localdev/scrabble-oracle-api:v0.0.2
    env_file:
      - app.env
    environment:
      - TPG_HOST=postgres
      - TPG_PORT=5432
    ports:
      - "5000:3000"
    volumes:
      - ./:/opt/build:default
    depends_on:
      - postgres
  postgres:
    image: "postgres:13-alpine"
    ports:
      - "1234:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./scripts/setup.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - db.env
volumes:
  postgres:
