FROM fpco/stack-build:lts-16.17 as scotty-build

RUN mkdir /opt/build
COPY . /opt/build
WORKDIR /opt/build
RUN stack build --copy-bins --resolver lts-16.17 --system-ghc    # uses GHC available on the path

EXPOSE $PORT
